### ISSUE TITLE
Build Action fails due to lack of lxd storage pool

### ISSUE THREAD

**Issue by codyshepherd** [jhenstridge/snapcraft-actions#8]
This action recently began failing during launching of the lxd container:

```
Run jhenstridge/snapcraft-build-action@v1
  with:
    path: .
Building Snapcraft project in "."...
Installing Snapcraft plus dependencies
  Installing Snapcraft...
  /usr/bin/sudo snap install --classic snapcraft
  snapcraft 4.5.1 from Canonical* installed
/usr/bin/sudo env SNAPCRAFT_BUILD_ENVIRONMENT=lxd snapcraft
Running with 'sudo' may cause permission errors and is discouraged. Use 'sudo' when cleaning.
Launching a container.
An error occurred with the instance when trying to launch with 'LXD': No storage pool found. Please create a new storage pool.
Ensure that 'LXD' is setup correctly and try again.
Error: The process '/usr/bin/sudo' failed with exit code 2
```

The yaml that uses the action is as follows:

```
name: Build Snap Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jhenstridge/snapcraft-build-action@v1
        id: snapcraft
      - name: install and test-run
        run: |
          snap --version
          snap list
          sudo snap install --devmode --dangerous ${{ steps.snapcraft.outputs.snap }}
```
